### ISSUE TITLE
If a message contains two links, only one will be saved

### ISSUE THREAD

**Issue by benco03** [benco03/JabberCamel#11]
Ideally should save both.

**Comment by sevagh** [comment]
What do you think of changing stripLink to return List<String> instead of String? That way you can easily support multiple URLs.

**Comment by sevagh** [comment]
private static List<String> stripLink(String message) throws Exception {
        String[] list = message.split(" ");
        ArrayList<String> url = new ArrayList<String>();

        for (int i = 0; i < list.length; i++) {
            if (list[i].contains("http")) {
                url.add(list[i]);
            }
        }
        if (url.isEmpty()) {
            throw new Exception("URL could not be found");
        } else {
            return url;
        }
    }

**Comment by benco03** [comment]
this has been fixed by @sevagh in 74312dfe17ae6a248ce1552f62eefa39d3e11883
